name: Newman Run
on:
  push:
    branches:
      - main

jobs:
  newman:
    name: Postman-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Install Newman & Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      # Make directory for test results in workspace
      - name: Make Directory
        run: mkdir -p newman-results
        
      # Run newman cli
      - name: Run Newman
        run: |
          newman run API_Newman_PassedTests.json -r htmlextra
     
      # Upload test results to workspace
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: Postman_Test_Report
          path: newman-results
